blank_issues_enabled: false
contact_links:
  - name: Check the docs
    url: https://beyondco.de/docs/tinkerwell/getting-started/about
    about: 'This repository is for reporting bugs and proposing new features. If you need help with your first steps of Tinkerwell, check out the docs!'
  - name: Security vulnerabilities
    url: https://beyondco.de
    about: If you want to report a security issue, please contact our support.
